/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar;

import java.sql.*;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author ANIS
 */
public class formDokter extends javax.swing.JFrame {
        Connection obj = null ;
	ResultSet rs = null;
	PreparedStatement pst = null;
	Statement statdok;
	Boolean ada = false;
    
    private void koneksi() throws SQLException {
        try {  
            Class.forName("oracle.jdbc.OracleDriver");  
            obj = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1522:XE","41520010221Dewi", "ganis");           

        } catch (ClassNotFoundException cnfe) {  
            
            }  
    }
    
    private void display(){
        try{
            String sql="select * from dokter";
            pst = obj.prepareStatement(sql);
            rs = pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    private void Clear(){
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
    }
    
    /**
     * Creates new form formDokter
     */
    public formDokter() {
        initComponents();
        obj = Connect.ConnectDB();
        display();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        TSimpan = new javax.swing.JButton();
        TEdit = new javax.swing.JButton();
        THapus = new javax.swing.JButton();
        TKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 160, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 160, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 160, -1));

        TSimpan.setText("Create");
        TSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(TSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        TEdit.setText("Edit");
        TEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEditActionPerformed(evt);
            }
        });
        getContentPane().add(TEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        THapus.setText("Delete");
        THapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                THapusActionPerformed(evt);
            }
        });
        getContentPane().add(THapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        TKeluar.setText("Exit");
        TKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(TKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel1.setText("ID Dokter");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel3.setText("Divisi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 420, 110));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("DATA DOKTER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void TSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TSimpanActionPerformed
        try{
            koneksi();
            statdok = obj.createStatement();
            String SQL = "insert into dokter values('"+jTextField1.getText()+"','"+jTextField2.getText()+"','"+jTextField3.getText()+"')";
            statdok.executeUpdate(SQL);
            display();
            statdok.close();
            obj.close();
            Clear();
            JOptionPane.showMessageDialog(null, "berhasil simpan");
            
        }catch(SQLException exc){
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_TSimpanActionPerformed

    private void TEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEditActionPerformed
        try{
            koneksi();
            statdok = obj.createStatement();
            String SQL = "update dokter SET id = '"+jTextField1.getText()+"', nama = '"+jTextField2.getText()+"', divisi = '"+jTextField3.getText()+"' WHERE id = '"+jTextField1.getText()+"'";
            statdok.executeUpdate(SQL);
            display();
            statdok.close();
            obj.close();
            Clear();
            JOptionPane.showMessageDialog(null, "berhasil edit");
           
        }catch(SQLException exc){
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_TEditActionPerformed

    private void THapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_THapusActionPerformed
        try{
            koneksi();
            statdok = obj.createStatement();
            String SQL = "DELETE FROM dokter WHERE id = '"+jTextField1.getText()+"'";
            statdok.executeUpdate(SQL);
            display();
            statdok.close();
            obj.close();
            JOptionPane.showMessageDialog(null, "berhasil hapus");
           
        }catch(SQLException exc){
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_THapusActionPerformed

    private void TKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_TKeluarActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        try {
            koneksi();
            int row =jTable2.getSelectedRow();
            String click = (jTable2.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = obj.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from dokter where id='"+click+"'");
            if(sql.next()){
                String id = sql.getString("id");
                jTextField1.setText(id);
                String nama = sql.getString("nama");
                jTextField2.setText(nama);
                String divisi = sql.getString("divisi");
                jTextField3.setText(divisi);
            }
        } catch (SQLException exc) {
            
        }
    }//GEN-LAST:event_jTable2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException exc) {
            java.util.logging.Logger.getLogger(formDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, exc);
        } catch (InstantiationException exc) {
            java.util.logging.Logger.getLogger(formDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, exc);
        } catch (IllegalAccessException exc) {
            java.util.logging.Logger.getLogger(formDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, exc);
        } catch (javax.swing.UnsupportedLookAndFeelException exc) {
            java.util.logging.Logger.getLogger(formDokter.class.getName()).log(java.util.logging.Level.SEVERE, null, exc);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TEdit;
    private javax.swing.JButton THapus;
    private javax.swing.JButton TKeluar;
    private javax.swing.JButton TSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
